[package]
name = "lanturn"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["cargo"] }
colored = "2.1.0"
crossterm = "0.28.1"
log = "0.4.22"
ratatui = "0.29.0"
reqwest = { version = "0.12.9", features = ["blocking"] }
simplelog = "0.12.2"
